name: Test requirements at repo root

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files and print requirements.txt
        run: |
            echo "PWD:"
            pwd
            echo "ROOT LISTING:"
            ls -la
            echo "---- requirements.txt ----"
            cat requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: pip install
        run: pip install -r requirements.txt
