name: Poll Telegram Replies

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (si requirements.txt existe)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: pip install -r requirements.txt

      - name: Poll and log
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python .github/workflows/scripts/poll_replies.py

      - name: Commit changes (CSV + state)
        run: |
          if [[ -n "$(git status --porcelain data/mood_log.csv state/last_update_id.txt 2>/dev/null)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/mood_log.csv state/last_update_id.txt
            git commit -m "Update mood log ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          fi
