name: Send Telegram Reminders

on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 12 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  send-9-15-21:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slot: ["09:00","15:00","21:00"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Send reminder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLOT: ${{ matrix.slot }}
        run: python scripts/send_reminder.py
