name: Send Reminder (root)

on:

 schedule:
    - cron: "0 6,12,18 * * *"   # 09:01 / 15:01 / 21:01 Helsinki
   
    
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files (debug)
        run: |
          pwd
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLOT: "09:00"
        run: python scripts/send_reminder.py
